name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: simple-app
  TAG: 20

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
            docker stop app || true
            docker rm app || true
            docker run -d -p 80:3000 --name app ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
